import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import os
import argparse
import time
import numpy as np
import sys

from models.Sample import HPP_sampling
from vit import ViT
from utils import get_if_data, MainConfig, AverageMeter, accuracy
from privacy_noise import generate_eta_r_fast


# Tee stdout to both terminal and log file.
class Logger(object):
    def __init__(self, filename='default.log', stream=sys.stdout):
        self.terminal = stream
        self.log = open(filename, 'a')
    def write(self, message):
        self.terminal.write(message)
        self.log.write(message)
        self.log.flush()
    def flush(self): pass


# KL-based knowledge distillation loss.
def distillation_loss(student_logits, teacher_logits, T=3.0):
    soft_targets = F.softmax(teacher_logits / T, dim=1)
    soft_prob = F.log_softmax(student_logits / T, dim=1)
    return F.kl_div(soft_prob, soft_targets, reduction='batchmean') * (T**2)


# Add training-time noise with static and null-space components.
def add_noise_with_eta_r(images, eta_c, R, lambda_noise, device, block_size):
    if lambda_noise == 0:
        return images

    B, C, H, W = images.shape
    N = block_size * block_size

    patches = F.unfold(images, kernel_size=block_size, stride=block_size)
    patches = patches.permute(0, 2, 1).contiguous().view(-1, N)

    total_blocks = patches.shape[0]

    eta_r = generate_eta_r_fast(R, total_blocks, p=0.5, device=device)
    eta_c_expanded = eta_c.unsqueeze(0).expand(total_blocks, N)

    scale = 2 * lambda_noise + 1
    noise_term = eta_c_expanded + eta_r
    patches_noisy = (patches + lambda_noise * noise_term) / scale

    patches_noisy = patches_noisy.view(B, -1, C*N).permute(0, 2, 1)
    noisy_images = F.fold(patches_noisy, output_size=(H, W), kernel_size=block_size, stride=block_size)

    return noisy_images


# Add validation-time noise with the static key component.
def add_noise_only_eta_c(images, eta_c, lambda_noise, block_size):
    if lambda_noise == 0:
        return images

    B, C, H, W = images.shape
    N = block_size * block_size

    patches = F.unfold(images, kernel_size=block_size, stride=block_size)
    patches = patches.permute(0, 2, 1).contiguous().view(-1, N)

    total_blocks = patches.shape[0]
    eta_c_expanded = eta_c.unsqueeze(0).expand(total_blocks, N)

    scale = 2 * lambda_noise + 1
    patches_noisy = (patches + lambda_noise * eta_c_expanded) / scale

    patches_noisy = patches_noisy.view(B, -1, C*N).permute(0, 2, 1)
    noisy_images = F.fold(patches_noisy, output_size=(H, W), kernel_size=block_size, stride=block_size)

    return noisy_images


# Train the noise-adapted User B inference model.
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--rate', default=0.25, type=float, help='采样率，如 0.1, 0.25')
    parser.add_argument('--device', default='0')
    parser.add_argument('--lr', default='1e-4')
    parser.add_argument('--epochs', default=50, type=int)
    parser.add_argument('--batch_size', default=64, type=int)
    parser.add_argument('--lambda_noise', default=1.0, type=float)
    parser.add_argument('--kd_weight', default=0.5, type=float)
    parser.add_argument('--temperature', default=3.0, type=float)


    parser.add_argument('--teacher_model_path', type=str, default=None,
                        help='教师模型路径 (默认根据 rate 自动生成)')
    parser.add_argument('--cs_sampling_path', type=str, default=None,
                        help='采样模型路径 (默认根据 rate 自动生成)')


    parser.add_argument('--key_dir', type=str, default='./')
    parser.add_argument('--eta_r_prob', default=0.5, type=float,
                        help='训练时使用 η_c+η_r 的概率 (0=只用η_c, 1=只用η_c+η_r)')

    opt = parser.parse_args()

    rate_folder = int(round(opt.rate * 100))

    if opt.teacher_model_path is None:
        opt.teacher_model_path = f'./results/HPP/{rate_folder}/models/if_model.pth'

    if opt.cs_sampling_path is None:
        opt.cs_sampling_path = f'./results/HPP/{rate_folder}/models/cs_sampling.pth'

    log_file = f'step2_fixed_rate_{opt.rate}_lambda_{opt.lambda_noise}.log'
    sys.stdout = Logger(log_file, sys.stdout)

    device = torch.device(f'cuda:{opt.device}' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")
    print(f"Rate: {opt.rate} (Loading from folder: {rate_folder})")
    print(f"λ = {opt.lambda_noise}, η_r 使用概率 = {opt.eta_r_prob}")
    print(f"Sampling Model Path: {opt.cs_sampling_path}")
    print(f"Teacher Model Path:  {opt.teacher_model_path}")


    # Load privacy assets generated by step1.
    eta_c_path = os.path.join(opt.key_dir, 'eta_c_key.pt')
    R_path = os.path.join(opt.key_dir, 'R_matrix_key.pt')

    if not os.path.exists(eta_c_path) or not os.path.exists(R_path):
        print(f"[ERROR] Keys not found at {opt.key_dir}")
        return

    eta_c_key = torch.load(eta_c_path).to(device)
    R_key = torch.load(R_path).to(device)

    config = MainConfig(opt.rate, opt.lr, opt.device)
    config.if_batch_size = opt.batch_size
    config.device = device


    cs_sampling = HPP_sampling(config.ratio, config.init_size).to(device)
    if os.path.exists(opt.cs_sampling_path):
        print(f"Loading Sampling Model from {opt.cs_sampling_path}")

        cs_sampling.load_state_dict(torch.load(opt.cs_sampling_path, map_location=device), strict=False)
    else:
        print(f"[WARNING] Sampling model not found at {opt.cs_sampling_path}, using random init!")

    cs_sampling.eval()
    for p in cs_sampling.parameters(): p.requires_grad = False


    # Teacher uses the clean HPP inference model.
    teacher_vit = ViT(config.arch, pretrained=False,
                      image_size=(config.img_size, config.img_size),
                      num_classes=1000).to(device)
    if os.path.exists(opt.teacher_model_path):
        print(f"Loading Teacher Model from {opt.teacher_model_path}")
        teacher_vit.load_state_dict(torch.load(opt.teacher_model_path, map_location=device), strict=False)
    else:
        print(f"[WARNING] Teacher model not found at {opt.teacher_model_path}!")

    teacher_vit.eval()
    for p in teacher_vit.parameters(): p.requires_grad = False


    # Student is adapted to protected measurements.
    student_vit = ViT(config.arch, pretrained=True,
                      image_size=(config.img_size, config.img_size),
                      num_classes=1000,
                      weights_path=config.pretrain_weight).to(device)


    train_loader, val_loader = get_if_data(config)
    optimizer = optim.AdamW(student_vit.parameters(), lr=float(opt.lr), weight_decay=1e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=opt.epochs)
    criterion = nn.CrossEntropyLoss().to(device)

    best_acc = 0
    save_path = f'user_b_vit_rate_{opt.rate}_lambda_{opt.lambda_noise}.pth'

    print(f"\n>> Start Training...")

    # Main User B training loop.
    for epoch in range(1, opt.epochs + 1):
        student_vit.train()
        losses = AverageMeter('Loss', ':.4f')
        top1 = AverageMeter('Acc@1', ':6.2f')

        for i, (images, target) in enumerate(train_loader):
            images = images.to(device, non_blocking=True)
            target = target.to(device, non_blocking=True)

            with torch.no_grad():

                teacher_feat = cs_sampling(images)
                teacher_logits = teacher_vit(teacher_feat)


                if np.random.rand() < opt.eta_r_prob:

                    images_noisy = add_noise_with_eta_r(
                        images, eta_c_key, R_key, opt.lambda_noise, device,
                        block_size=config.init_size
                    )
                else:

                    images_noisy = add_noise_only_eta_c(
                        images, eta_c_key, opt.lambda_noise,
                        block_size=config.init_size
                    )

                student_feat = cs_sampling(images_noisy)

            student_logits = student_vit(student_feat)

            loss_cls = criterion(student_logits, target)
            loss_kd = distillation_loss(student_logits, teacher_logits, T=opt.temperature)
            loss = loss_cls + opt.kd_weight * loss_kd

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            acc1, _ = accuracy(student_logits, target, topk=(1, 5))
            losses.update(loss.item(), images.size(0))
            top1.update(acc1[0], images.size(0))

            if i % 50 == 0:
                print(f"  Ep[{epoch}][{i}/{len(train_loader)}] Loss:{loss.item():.3f} Acc:{acc1[0]:.2f}%")

        scheduler.step()


        student_vit.eval()
        val_top1 = AverageMeter('Val@1', ':6.2f')

        with torch.no_grad():
            for images, target in val_loader:
                images = images.to(device)
                target = target.to(device)

                images_noisy = add_noise_only_eta_c(
                    images, eta_c_key, opt.lambda_noise,
                    block_size=config.init_size
                )

                feat = cs_sampling(images_noisy)
                output = student_vit(feat)
                acc1, _ = accuracy(output, target, topk=(1, 5))
                val_top1.update(acc1[0], images.size(0))

        print(f"Epoch {epoch} Val Acc: {val_top1.avg:.2f}% (Best: {best_acc:.2f}%)")

        if val_top1.avg > best_acc:
            best_acc = val_top1.avg
            torch.save(student_vit.state_dict(), save_path)
            print(f"   *** Saved Best Model to {save_path} ***")

    print(f"\nTraining Complete! Best Val Acc: {best_acc:.2f}%")


if __name__ == '__main__':
    main()